#!/usr/bin/env bash
# comments here
IFS=":"


while read -r col1 col2 col3 col4 col5 col6 col7; do 

echo "The user $col1 is part of the $col4 gang, lives in $col6 and rides $col7. $col3 place is protected by the passcode $col2, more info about the user here: $col5"
   
	    done <  /etc/passwd
shellcheck 12-tell_the_story_of_passwd
