#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
export a=1
while [ $a -lt 10 ]
do
    echo "Best School"
    ((a += 1))
    if [[ $a -eq 9 ]]
    then
	echo "Hi"
	
    fi
done
shellcheck 4-if_9_say_hi
