#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
export a=0
while [ $a -lt 10 ]
do
    if [[ $a -eq 3 ]]
    then
	echo "bad luck"
    elif [[ $a -eq 7 ]]
	 then
	 echo "good luck"
    else
	echo "Best School"
    fi
    ((a += 1))
done
shellcheck 5-4_bad_luck_8_is_your_chance
