#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
export a=0
export b=0

while [ $b -lt 13 ]
do
    if [[ $b -eq 0 ]]
    then
	echo "$b hours"
	 (( b += 1))
    elif [[ $a = 60]]  
    then
	(( a = 0 ))
	
     
        echo "$b hours"
	(( b += 1 ))
	
    
    else
  
	    echo "$a"
	   
    fi
    ((a += 1))
done
   
shellcheck 7-clock
