#!/usr/bin/env bash
#own
echo $$ > /var/run/myscript.pid
trap 'echo I hate the kill command; rm -f /var/run/myscript.pid; exit' TERM
trap 'echo "Y U no love me?!"; exit' INT
trap 'rm -f /var/run/myscript.pid; exit' QUIT

while [ -f /var/run/myscript.pid ]; do
    echo To infinity and beyond
    sleep 2
done



shellcheck 10-process_and_pid_file
